

export const ErrorCodes = Object.freeze({

    DB_DUPLICATE_ENTRY: 'DB_DUPLICATE_ENTRY',
    
    GEN_VALIDATION_FAILED: 'GEN_VALIDATION_FAILED',
    GEN_INTERNAL_ERROR: 'GEN_INTERNAL_ERROR',
    GEN_FORBIDDEN_ACCESS: 'GEN_FORBIDDEN_ACCESS',
    GEN_UPDATE_FAILED: 'GEN_UPDATE_FAILED',
    
    ROLE_DUPLICATE_NAME: 'ROLE_DUPLICATE_NAME',
    ROLE_INSUFFICIENT_LEVEL: 'ROLE_INSUFFICIENT_LEVEL',
    ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',

    ORG_NOT_MEMBER:'ORG_NOT_MEMBER',
    ORG_NOT_FOUND:'ORG_NOT_FOUND',
    ORG_NOT_ENOUGH_ACCESS: 'ORG_NOT_ENOUGH_ACCESS',

    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_EXISTS: 'USER_EXISTS',

    INVALID_PASSWORD: 'INVALID_PASSWORD',
    AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED'
});

export const SuccessCodes = Object.freeze({
    ROLE_CHANGED_SUCCESSFULLY: 'ROLE_CHANGED_SUCCESSFULLY',
    USER_UPDATED_SUCCESSFULLY: 'USER_UPDATED_SUCCESSFULLY',
    ORG_CREATED_SUCCESSFULLY: 'ORG_CREATED_SUCCESSFULLY',
    ORG_UPDATED_SUCCESSFULLY: 'ORG_UPDATED_SUCCESSFULLY'
})